### ISSUE TITLE
support rails 5.2.0.rc1?

### ISSUE THREAD

**Issue by jrochkind** [thuss/standalone-migrations#140]

**Comment by jmehnle** [comment]
I tracked down the change where the maximum (exclusive) `activerecord` version was bumped from 5.1.0 to 5.2.0 (5d084efb), and it seems like there were no other changes required to make it work on 5.1.0, so I'm wondering: can we bump the version range to `[">= 4.2.7", "< 5.3.0"]`?

**Comment by thuss** [comment]
I prefer to wait until the version has been officially released so that the unit tests are running against the latest stable production version. If we were to bump to 5.3.0 now in the gem file the unit tests would be still be testing against 5.1.x and then if 5.2.0 is released it would satisfy the dependency but possibly have issues. Once it's out (which should be soon) I'd be happy to bump it.

I'll leave this issue open as a reminder for when the time comes.
